# docker-compose.yml
# UPDATED: Now runs Alembic migrations on startup and removes the .sql volume mount.

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitbud_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    
    depends_on:
      db:
        condition: service_healthy
    # COMMAND UPDATED: First, run migrations to ensure DB is up to date.
    # Then, start the Uvicorn server with hot-reloading for development.
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"


  db:
    image: postgres:15-alpine
    container_name: fitbud_db
    volumes:
      # Mount the main data directory
      - postgres_data:/var/lib/postgresql/data/
      # Mount our new initialization script
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=fitbud_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=fitbud_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
