"""data_migration_move_goals

Revision ID: 01e82ed2625a
Revises: 368b647a8d7b
Create Date: 2025-08-16 08:39:57.977044+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '01e82ed2625a' # Keep the ID Alembic generated
down_revision: Union[str, None] = '368b647a8d7b' # Keep the ID Alembic generated
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Moving data from goal_description to goal...")
    # This SQL command copies the data and then clears the old column.
    op.execute(
        """
        UPDATE clients
        SET goal = goal_description,
            goal_description = NULL
        WHERE goal_description IS NOT NULL;
        """
    )
    print("Data migration complete.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Moving data from goal back to goal_description...")
    # This reverses the process if you ever need to downgrade.
    op.execute(
        """
        UPDATE clients
        SET goal_description = goal,
            goal = NULL
        WHERE goal IS NOT NULL;
        """
    )
    print("Data migration downgrade complete.")