"""make_client_user_id_nullable

Revision ID: 09aec22a1c52
Revises: dba6708623df
Create Date: 2025-08-13 11:45:49.525221+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09aec22a1c52'
down_revision: Union[str, None] = 'dba6708623df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'client_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'client_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###