"""add_invited_name_email_to_clients

Revision ID: 2db85ddf47f7
Revises: 09aec22a1c52
Create Date: 2025-08-13 12:04:13.135313+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db85ddf47f7'
down_revision: Union[str, None] = '09aec22a1c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('invited_full_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('invited_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'invited_email')
    op.drop_column('clients', 'invited_full_name')
    # ### end Alembic commands ###