"""rename_goal_description_and_add_new_goal_fields

Revision ID: 368b647a8d7b
Revises: e055145a50c7
Create Date: 2025-08-16 08:06:52.217028+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368b647a8d7b'
down_revision: Union[str, None] = 'e055145a50c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'goal')
    # ### end Alembic commands ###