"""Add plan_structure to template tables

Revision ID: 8a7b3c2d1f0e
Revises: d48a52c39a5c
Create Date: 2025-08-12 13:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a7b3c2d1f0e'
down_revision: Union[str, None] = 'd48a52c39a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding a NOT NULL column can fail on existing databases with rows.
    # Use a temporary server_default so the ALTER TABLE succeeds, then drop it.
    jsonb_type = postgresql.JSONB(astext_type=sa.Text())

    op.add_column(
        "diet_plan_templates",
        sa.Column("plan_structure", jsonb_type, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )
    op.add_column(
        "workout_plan_templates",
        sa.Column("plan_structure", jsonb_type, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )

    # Drop defaults so application controls required payloads going forward.
    op.alter_column("diet_plan_templates", "plan_structure", server_default=None, existing_type=jsonb_type)
    op.alter_column("workout_plan_templates", "plan_structure", server_default=None, existing_type=jsonb_type)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plan_templates', 'plan_structure')
    op.drop_column('diet_plan_templates', 'plan_structure')
    # ### end Alembic commands ###
