"""add_payment_status_to_clients

Revision ID: 8ed3bb18f0e4
Revises: 01e82ed2625a
Create Date: 2025-08-18 09:34:50.953451+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed3bb18f0e4'
down_revision: Union[str, None] = '01e82ed2625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('payment_status', sa.String(), nullable=True))
    op.alter_column('clients', 'goal_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'goal_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('clients', 'payment_status')
    # ### end Alembic commands ###