"""Add private_notes to clients table

Revision ID: 9c7b5a3e1f0d
Revises: 8a7b3c2d1f0e
Create Date: 2025-08-12 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7b5a3e1f0d'
down_revision: Union[str, None] = '8a7b3c2d1f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('private_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'private_notes')
    # ### end Alembic commands ###
