"""partial unique constraints for libraries

Revision ID: a6d5d05072a3
Revises: d0e71ddfea55
Create Date: 2026-03-17 10:31:24.749171+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d5d05072a3'
down_revision: Union[str, Sequence[str], None] = 'd0e71ddfea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_exercise_trainer'), 'exercise_library', type_='unique')
    op.create_index('uq_trainer_exercise', 'exercise_library', ['name', 'owner_trainer_id'], unique=True, postgresql_where=sa.text('is_verified = false'))
    op.create_index('uq_verified_exercise', 'exercise_library', ['name'], unique=True, postgresql_where=sa.text('is_verified = true'))
    op.drop_constraint(op.f('uq_food_trainer'), 'food_item_library', type_='unique')
    op.create_index('uq_trainer_food', 'food_item_library', ['name', 'owner_trainer_id'], unique=True, postgresql_where=sa.text('is_verified = false'))
    op.create_index('uq_verified_food', 'food_item_library', ['name'], unique=True, postgresql_where=sa.text('is_verified = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_verified_food', table_name='food_item_library', postgresql_where=sa.text('is_verified = true'))
    op.drop_index('uq_trainer_food', table_name='food_item_library', postgresql_where=sa.text('is_verified = false'))
    op.drop_index('uq_verified_exercise', table_name='exercise_library', postgresql_where=sa.text('is_verified = true'))
    op.drop_index('uq_trainer_exercise', table_name='exercise_library', postgresql_where=sa.text('is_verified = false'))
    op.create_unique_constraint(op.f('uq_food_trainer'), 'food_item_library', ['name', 'owner_trainer_id'])
    op.create_unique_constraint(op.f('uq_exercise_trainer'), 'exercise_library', ['name', 'owner_trainer_id'])
    # ### end Alembic commands ###
