"""Sync V2 architecture

Revision ID: ad6628cb74f6
Revises: ba6c5f27bacc
Create Date: 2026-03-06 18:41:17.724817+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad6628cb74f6'
down_revision: Union[str, Sequence[str], None] = 'ba6c5f27bacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_trainer_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('base_unit_type', sa.String(), nullable=True),
    sa.Column('grams_per_ml', sa.Numeric(), nullable=True),
    sa.Column('calories_per_100g', sa.Integer(), nullable=True),
    sa.Column('protein_per_100g', sa.Numeric(), nullable=True),
    sa.Column('carbs_per_100g', sa.Numeric(), nullable=True),
    sa.Column('fat_per_100g', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diet_template_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('food_item_id', sa.UUID(), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('serving_size', sa.Numeric(), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item_library.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['diet_plan_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_template_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('target_sets', sa.String(), nullable=True),
    sa.Column('target_reps', sa.String(), nullable=True),
    sa.Column('rest_period_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_plan_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity_feed', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('activity_feed', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # op.drop_index(op.f('activity_feed_client_id_event_timestamp_desc_idx'), table_name='activity_feed')
    op.drop_column('activity_feed', 'metadata')
    # op.drop_index(op.f('assigned_diet_plans_client_id_idx'), table_name='assigned_diet_plans')
    # op.drop_index(op.f('assigned_diet_plans_source_template_id_idx'), table_name='assigned_diet_plans')
    # op.drop_index(op.f('assigned_workout_plans_client_id_idx'), table_name='assigned_workout_plans')
    # op.drop_index(op.f('assigned_workout_plans_source_template_id_idx'), table_name='assigned_workout_plans')
    op.alter_column('checkins', 'progress_photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('checkins', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_index(op.f('checkins_client_id_checked_in_at_desc_idx'), table_name='checkins')
    op.add_column('clients', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('invited_full_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('invited_email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('subscription_due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('subscription_paid_status', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('initial_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('clients', sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('clients', sa.Column('health_notes', sa.Text(), nullable=True))
    op.alter_column('clients', 'client_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'invited'::text"))
    op.alter_column('clients', 'invite_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_index(op.f('clients_client_user_id_idx'), table_name='clients')
    # op.drop_index(op.f('clients_trainer_user_id_idx'), table_name='clients')
    # op.drop_index(op.f('clients_trainer_user_id_status_idx'), table_name='clients')
    op.create_index(op.f('ix_clients_client_status'), 'clients', ['client_status'], unique=False)
    op.alter_column('diet_logs', 'meal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('diet_logs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # op.drop_index(op.f('diet_logs_client_id_logged_at_desc_idx'), table_name='diet_logs')
    op.alter_column('diet_plan_templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('diet_plan_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_index(op.f('diet_plan_templates_parent_template_id_idx'), table_name='diet_plan_templates')
    # op.drop_index(op.f('diet_plan_templates_trainer_id_idx'), table_name='diet_plan_templates')
    op.drop_column('diet_plan_templates', 'plan_structure')
    op.add_column('exercise_library', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('exercise_library', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # op.drop_index(op.f('exercise_library_owner_trainer_id_idx'), table_name='exercise_library')
    op.create_unique_constraint(None, 'exercise_library', ['name'])
    # op.drop_constraint(op.f('exercise_library_owner_trainer_id_fkey'), 'exercise_library', type_='foreignkey')
    # op.create_foreign_key(None, 'exercise_library', 'users', ['owner_trainer_id'], ['id'])
    op.drop_column('exercise_library', 'video_url')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'user_role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'profile_photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_index(op.f('workout_logs_client_id_logged_at_desc_idx'), table_name='workout_logs')
    op.alter_column('workout_plan_templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workout_plan_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_index(op.f('workout_plan_templates_parent_template_id_idx'), table_name='workout_plan_templates')
    # op.drop_index(op.f('workout_plan_templates_trainer_id_idx'), table_name='workout_plan_templates')
    op.drop_column('workout_plan_templates', 'plan_structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plan_templates', sa.Column('plan_structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_index(op.f('workout_plan_templates_trainer_id_idx'), 'workout_plan_templates', ['trainer_id'], unique=False)
    op.create_index(op.f('workout_plan_templates_parent_template_id_idx'), 'workout_plan_templates', ['parent_template_id'], unique=False)
    op.alter_column('workout_plan_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workout_plan_templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('workout_logs_client_id_logged_at_desc_idx'), 'workout_logs', ['client_id', sa.literal_column('logged_at DESC')], unique=False)
    op.alter_column('users', 'profile_photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'user_role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('exercise_library', sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercise_library', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_library_owner_trainer_id_fkey'), 'exercise_library', 'users', ['owner_trainer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'exercise_library', type_='unique')
    op.create_index(op.f('exercise_library_owner_trainer_id_idx'), 'exercise_library', ['owner_trainer_id'], unique=False)
    op.alter_column('exercise_library', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('exercise_library', 'is_verified')
    op.add_column('diet_plan_templates', sa.Column('plan_structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_index(op.f('diet_plan_templates_trainer_id_idx'), 'diet_plan_templates', ['trainer_id'], unique=False)
    op.create_index(op.f('diet_plan_templates_parent_template_id_idx'), 'diet_plan_templates', ['parent_template_id'], unique=False)
    op.alter_column('diet_plan_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('diet_plan_templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('diet_logs_client_id_logged_at_desc_idx'), 'diet_logs', ['client_id', sa.literal_column('logged_at DESC')], unique=False)
    op.alter_column('diet_logs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('diet_logs', 'meal_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_clients_client_status'), table_name='clients')
    op.create_index(op.f('clients_trainer_user_id_status_idx'), 'clients', ['trainer_user_id', 'client_status'], unique=False)
    op.create_index(op.f('clients_trainer_user_id_idx'), 'clients', ['trainer_user_id'], unique=False)
    op.create_index(op.f('clients_client_user_id_idx'), 'clients', ['client_user_id'], unique=False)
    op.alter_column('clients', 'invite_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clients', 'client_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'invited'::text"))
    op.drop_column('clients', 'health_notes')
    op.drop_column('clients', 'height_cm')
    op.drop_column('clients', 'initial_weight_kg')
    op.drop_column('clients', 'payment_status')
    op.drop_column('clients', 'subscription_paid_status')
    op.drop_column('clients', 'subscription_due_date')
    op.drop_column('clients', 'invited_email')
    op.drop_column('clients', 'invited_full_name')
    op.drop_column('clients', 'goal')
    op.create_index(op.f('checkins_client_id_checked_in_at_desc_idx'), 'checkins', ['client_id', sa.literal_column('checked_in_at DESC')], unique=False)
    op.alter_column('checkins', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('checkins', 'progress_photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('assigned_workout_plans_source_template_id_idx'), 'assigned_workout_plans', ['source_template_id'], unique=False)
    op.create_index(op.f('assigned_workout_plans_client_id_idx'), 'assigned_workout_plans', ['client_id'], unique=False)
    op.create_index(op.f('assigned_diet_plans_source_template_id_idx'), 'assigned_diet_plans', ['source_template_id'], unique=False)
    op.create_index(op.f('assigned_diet_plans_client_id_idx'), 'assigned_diet_plans', ['client_id'], unique=False)
    op.add_column('activity_feed', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('activity_feed_client_id_event_timestamp_desc_idx'), 'activity_feed', ['client_id', sa.literal_column('event_timestamp DESC')], unique=False)
    op.alter_column('activity_feed', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('activity_feed', 'event_metadata')
    op.drop_table('workout_template_items')
    op.drop_table('diet_template_items')
    op.drop_table('food_item_library')
    # ### end Alembic commands ###
