"""fix library uniqueness constraints

Revision ID: d0e71ddfea55
Revises: ad6628cb74f6
Create Date: 2026-03-14 01:28:58.429774+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e71ddfea55'
down_revision: Union[str, Sequence[str], None] = 'ad6628cb74f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercise_library_name_key'), 'exercise_library', type_='unique')
    op.create_unique_constraint('uq_exercise_trainer', 'exercise_library', ['name', 'owner_trainer_id'])
    op.drop_constraint(op.f('food_item_library_name_key'), 'food_item_library', type_='unique')
    op.create_unique_constraint('uq_food_trainer', 'food_item_library', ['name', 'owner_trainer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_food_trainer', 'food_item_library', type_='unique')
    op.create_unique_constraint(op.f('food_item_library_name_key'), 'food_item_library', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_exercise_trainer', 'exercise_library', type_='unique')
    op.create_unique_constraint(op.f('exercise_library_name_key'), 'exercise_library', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
