"""add_subscription_and_details_to_clients

Revision ID: e055145a50c7
Revises: 2db85ddf47f7
Create Date: 2025-08-14 11:37:08.926144+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e055145a50c7'
down_revision: Union[str, None] = '2db85ddf47f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('subscription_due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('subscription_paid_status', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('initial_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('clients', sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('clients', sa.Column('health_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'health_notes')
    op.drop_column('clients', 'height_cm')
    op.drop_column('clients', 'initial_weight_kg')
    op.drop_column('clients', 'subscription_paid_status')
    op.drop_column('clients', 'subscription_due_date')
    # ### end Alembic commands ###